site_name: Summary Note

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Nanum Gothic
  icon:
    annotation: material/plus-circle
  language: en
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs

extra:
  alternate:
    - name: Korean
      link: /ko/
      lang: ko
    - name: English
      link: /en/
      lang: en

plugins:
  - search
  # - macros
  - tags:
      tags_file: tags.md
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      categories: true
      categories_name: Categories
      # categories_toc: true
      pagination: true
      pagination_per_page: 5

hooks:
  - my_hook.py

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      base_path:
        - !relative
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - ko:
    - Home: ko/index.md
    - Hello:
      - ko/hello/hello.md
    - 자료구조:
      - 알고리즘: ko/datastructures/algorithms.md
      - 자구: ko/datastructures/datastructures.md
    - Test: test.md
  - en:
    - DS:
      - algo: en/datastructures/algorithms.md
      - ds: en/datastructures/datastructures.md
  # - google: "https://google.com"